### ISSUE TITLE
Debug output support

### ISSUE THREAD

**Issue by MOZGIII** [auth0/k8s-pixy-auth#16]
I have an issue with this tool, and I'd like to have a better way to debug it.
Printing more logs if requested is a viable solution to me.

**Comment by grounded042** [comment]
Hey @MOZGIII I'm sorry for not getting back to you sooner! More logs is a very general request, but we are happy to review any pull requests or look at more specifics you could give.

**Comment by grounded042** [comment]
As there has been no update on this ticket in several months I'm going to close it. If this is still an issue you would like to pursue, please comment and re-open the issue.
