### ISSUE TITLE
Auth credentials are not preserved on Ubuntu 18.04

### ISSUE THREAD

**Issue by MOZGIII** [auth0/k8s-pixy-auth#19]
When I'm using the system, auth credentials are asked every time (on every `kubectl` command the browser opens) and are not persisted. Technically, I'm not even using `master` (cause it's simply broken on Ubuntu), but the code from #18. Apparently, the `keyring` update makes auth flow not stuck, but it still doesn't work as it's supposed to.
See also: #17

**Comment by grounded042** [comment]
I used this to debug for Ubuntu: https://github.com/auth0/k8s-pixy-auth/blob/b218dee6584eb12d0470f337993be74065d4c02c/docs/DockerTestingForUbuntu.md and did not have any problems. Would you be able to run through that and see if it works or not? I'm not sure why it's working for me and not for you.

**Comment by grounded042** [comment]
As there has been no update on this ticket in several months I'm going to close it. If this is still an issue you would like to pursue, please comment and re-open the issue.
