### ISSUE TITLE
Support for application/x-www-form-urlencoded for token API requests

### ISSUE THREAD

**Issue by venushka** [auth0/k8s-pixy-auth#20]
I was trying to use k8s-pixy-auth with the auth provider we use in our organisation and found that it expects token API requests to be submitted with the content type `application/x-www-form-urlencoded`, so it fails with 400 Bad Request when trying to login. Had a look through the OAuth 2.0 spec, and it says to use `application/x-www-form-urlencoded` here: https://tools.ietf.org/html/rfc6749#section-4.3.2

Looking at `authorization_tokenretriever.go`, k8s-pixy-auth is using `application/json` which I assume something that works with most auth providers? Will you consider supporting `application/x-www-form-urlencoded` token API requests as well possibly via specifying a command line flag to indicate which content type to use? Or switch to `application/x-www-form-urlencoded` without using `application/json` if it makes this more compliant with the spec?

**Comment by grounded042** [comment]
Hey @venushka. Sorry for taking so long to get back to you! Nice find on that. If the spec has it that way then we should support that or probably even switch that to just use `application/x-www-form-urlencoded`. I'm not sure when I'll have the time in the coming weeks to add that in, but I'll try to prioritize it. We'd also welcome a PR!

**Comment by grounded042** [comment]
This has been fixed and released in [v0.3.3](https://github.com/auth0/k8s-pixy-auth/releases/tag/v0.3.3). Thanks for the report @venushka!
