### ISSUE TITLE
Unable to use cached token using "freedesktop.secretservice" backend

### ISSUE THREAD

**Issue by pandaren89** [auth0/k8s-pixy-auth#24]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When executing `kubectl` via `k8s-pixy-auth` binary using freedesktop secret service backend, it is possible to get tokens from the K8s apiserver and properly cached.(This is visible using seahorse), and the kubectl command works. 

However,when executing the `kubectl` again, it's not possible to use the cached token, instead it initialize the Authn journey again with the browser. 

### Reproduction

> Detail the steps taken to reproduce this error, what was expected, and whether this issue can be reproduced consistently or if it is intermittent.
>
> Where applicable, please include:
>
Using freedesktop secret service backend in a Linux OS,

configure the K8S cluster according to the guide,

configure the kubeconfig file according the guide,

execute `kubectl get nodes` ---> `browser auth` -> `successful result`

execute `kubectl get nodes` ---> `browser auth` -> `successful result`

The desired behaviour is supposed to use the cached token in the `freedesktop.secretservice` and the second time authentication is not needed.

I will open a PR about this tiny fix. 

### Environment

> Please provide the following:

- **Version of this library used: master
- **Version of the platform or framework used, if applicable: go.1.12
- **Other relevant versions (language, server software, OS, browser): Fedora 30, Fedora 31, Chromium browser
- **Other modules/plugins/libraries that might be involved: keyring, libsecret, go-dbus.

**Comment by grounded042** [comment]
This has been fixed and released in [v0.3.3](https://github.com/auth0/k8s-pixy-auth/releases/tag/v0.3.3). Thanks for the report and contribution @pandaren89!
