### ISSUE TITLE
 Which client id？

### ISSUE THREAD

**Issue by kenta-r** [auth0/k8s-pixy-auth#28]
## There are two questions.
>13.Make sure you've put in the client ID you saved from step 5 and save the rule. 
I'm having trouble, so I want to check.
Is step5 the Client ID of "minikube-login Native"?

>--client-id "QXV0aDAgaXMgaGlyaW5nISBhdXRoMC5jb20vY2FyZWVycyAK"
Client ID of "minikube-login Native"?

**Comment by grounded042** [comment]
> Is step5 the Client ID of "minikube-login Native"?
Correct, the application you created.

> Client ID of "minikube-login Native"?
The same Client ID from the previous answer.

Let me know if that works for you.

**Comment by kenta-r** [comment]
Thank you!

Said well!
