### ISSUE TITLE
Support Windows SubSystem for Linux

### ISSUE THREAD

**Issue by traviisd** [auth0/k8s-pixy-auth#32]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

With Windows SubSystem for Linux becoming very popular, some additional checks would be needed to account for it as the "xdg-open" command does not work. However, `cmd.exe /c start ...` is supported.

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

### Describe the ideal solution

> A clear and concise description of what you want to happen.

Modify the function OpenURL within os/os_interactor.go line 17, and add a couple helper functions to determine WSL.
```golang
// OpenURL opens the passed in url in the default OS browser
func (i *DefaultInteractor) OpenURL(url string) error {
	var cmd string
	var args []string

	switch runtime.GOOS {
	case "windows":
		cmd = "cmd"
		args, url = i.BuildWindowsAgsAndURL(url)
	case "darwin":
		cmd = "open"
	default: // "linux", "freebsd", "openbsd", "netbsd"
		if i.IsWSL() {
			cmd = "cmd.exe"
			args, url = i.BuildWindowsAgsAndURL(url)
		} else {
			cmd = "xdg-open"
		}
	}

	args = append(args, url)

	return exec.Command(cmd, args...).Start()
}

...

// IsWSL runs the "uname -a" command to see if the output contains "microsoft" and returns true if it does, else false.
// This is so we can check if the Linux OS is actually Windows SubSystem for Linux, which requires
// A different command to open a browser.
func (i DefaultInteractor) IsWSL() bool {
	b, err := exec.Command("uname", "-a").Output()
	if err != nil {
		fmt.Printf("\nWarning: %s\n", err.Error())
		return false
	}

	if strings.Contains(strings.ToLower(string(b)), "microsoft") {
		return true
	}

	return false
}

// BuildWindowsAgsAndURL builds the command args and escapes the url for the Windows command to open a browser.
// The character & is treated as running a separate command in Windows
// cmd /c start "http://domain.com?param1&param2" results in trying to run cmd /c "start http://domain.com?parm1" & param2
// Also, the " char is used as the delimiter to escape special characters, so "&" would become \&\
// cmd /c start 'http://domain.com?param1=value with space"&"param2=value2' works when inputting directly to the command prompt,
// but the "&" is escaped by \"&\" when passed from code, which becomes \&\, resulting in cmd /c start 'http://domain.com?param1\&\param2'
// The start command uses ^ to escape special characters
func (i DefaultInteractor) BuildWindowsAgsAndURL(url string) (args []string, escapedURL string) {
	return []string{"/c", "start"},
		strings.ReplaceAll(strings.ReplaceAll(url, " ", "%20"), "&", `^&`)
}
```

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

I'm unsure of any other solutions aside from installing/requiring 3rd party scripts/tools.

### Additional context

> Add any other context or screenshots about the feature request here.

I tested the code and it works well on WSL (some real values taken out):

```
/mnt/c$ ./k8s-pixy-auth auth   --issuer-endpoint "https://ISSUER.COM"   --audience "AUDIENCE"   --client-id "CLIENTID"   --use-id-token
in the future you can set KEYRING_K8S_PIXY_AUTH_PASSWORD to bypass this prompt
Enter passphrase to unlock /home/traviisd/.k8s-pixy-auth: {"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{},"status":{"token":"THE JWT YAY!"}}
```

**Comment by traviisd** [comment]
I have the code ready if this is something that would be desired.

**Comment by grounded042** [comment]
Hey @traviisd, nice work on this. Happy to accept a PR!
